environment_config:
  n_agents: 10
  n_dim: 2
  ep_length: 20
  minimize: False
  freeze: True
  fraq_refinement: 0.5
  env_list: [sphere, rosenbrock, cosine_mixture, ghabit, cos_function, ackley, rastrigin, griewank, bohachevsky, booth, three_hump_camel, easom, six_hump_camel]
  bounds: [[(-3, 3),(-3, 3)], [(-3, 3), (-2, 2)]]
  max_episode: 50
  plot_directory: plots/
  fps: 2



policy_config:
  state_dim: 4
  action_dim: 1
  init_std: 0.2
  std_min: 0.001
  std_max: 0.2
  std_type: linear
  fixed_std: False
  hidden_dim: [32,32,32]
  episode_length: 20
  betas: 0.999
  lr: 0.00001
  gamma: 0.9
  K_epochs: 32
  eps_clip: 0.2
  initialization: 
  pretrained: False
  ckpt_path: 
  split_agent: True
  split_fraq: 0.5
  explore_state_dim: 4
  exploit_state_dim: 4
  update_interval: 10
  save_interval: 100
  model_path: models
  

environment:
  max_episodes: 50000
  change_env: 5
  update_timestep: 200
  save_freq: 500
  log_freq: 500
  std_type: euclidean
  ep_length: 100
  print_freq: 500
  save_cutoff: 100
  transition_episode: 1000