environment_config:
  n_agents: 14
  n_dim: 2
  ep_length: 30
  freeze: True
  fraq_refinement: 0.5
  env_list: [sphere, rosenbrock, cosine_mixture, ghabit, cos_function, ackley, rastrigin, griewank, bohachevsky, booth, three_hump_camel, easom, six_hump_camel]
  bounds: [[(-3, 3),(-3, 3)], [(-3, 3), (-2, 2)]]
  max_episode: 20001
  plot_directory: plots/
  gif_directory: gifs/
  fps: 1
  env_id: [2, 3, 4]
  change_freq: 2000
  log_directory: logs/
  log_interval: 100



policy_config:
  state_dim: 6
  action_dim: 1
  init_std: 0.2
  std_min: 0.02
  std_max: 0.4
  std_type: linear
  fixed_std: False
  hidden_dim: [16, 16]
  episode_length: 30
  betas: 0.999
  lr: 0.00001
  gamma: 0.9
  K_epochs: 32
  eps_clip: 0.2
  initialization: 
  pretrained: False
  ckpt_path: 
  split_agent: True
  split_fraq: 0.5
  explore_state_dim: 6
  exploit_state_dim: 6
  update_interval: 10
  save_interval: 2000
  model_path: models/
  test_model_path: models/20230111-090458_model/_20000
  animate_interval: 2000
  std_decay_freq: 100
  std_decay_rate: 0.001
  std_obs_type: distance
  

test_policy_config:
  state_dim: 6
  action_dim: 1
  init_std: 0.005
  std_min: 0.2
  std_max: 0.5
  std_type: linear
  fixed_std: False
  hidden_dim: [16, 16]
  ep_length: 30
  betas: 0.999
  lr: 0.00001
  gamma: 0.9
  K_epochs: 32
  eps_clip: 0.2
  initialization: 
  pretrained: False
  ckpt_path: 
  split_agent: True
  split_fraq: 0.5
  explore_state_dim: 6
  exploit_state_dim: 6
  update_interval: 10
  save_interval: 2000
  model_path: models/
  test_model_path: models/20230111-090458_model/_20000
  animate_interval: 2000
  std_decay_freq: 100
  std_decay_rate: 0.001
  std_obs_type: distance